// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yopolvxzmocntpmxvjpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvcG9sdnh6bW9jbnRwbXh2anBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzI4OTEsImV4cCI6MjA2ODYwODg5MX0.QjWxHmsPdBtEVnowgJwMT3Al8BMpPwnXH2rC6PqmStk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});